version: '3.8'

services:
  nginx:
    image: nginx:latest  
    ports:
      - 80:80
      - 443:443
    container_name: server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www/:/etc/nginx/www/
      - ./cert:/etc/nginx/cert/

